###########################################
# User service
###########################################

system:
  id: test
  listen: 0.0.0.0
  port: 8000
  root: /app
  salt: change-for-production

memory:
  type: redis
  model: direct
  host: localhost
  port: 6379

db:
  type: mongo
  host: localhost

auth:
  bearerTokenTTL: 3600 # default

registry:
  services:
    user-service:
      name: User service
      specs:
        - /user.yaml
      handlers:
        - /handlers

user:
  defaultRole: member
  adminRole: admin
  passwordLength: 8
  meta:
    fname:
      mandatory: true
      message: Missing first name
    lname:
      mandatory: true
      message: Missing last name
    username:
      mandatory: false
    avatar:
      mandatory: false

  users:
    - email: testadmin@frogfish.io
      password: testpassword
      roles:
        - admin
