name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1.1.0
    - uses: actions/checkout@v1
    - name: Install packages
      run: npm install --no-bin-links
    - name: build service
      run: npm build
    - uses: manusa/actions-publish-docker@v1.0.1
      with:
        # Name of the Docker image
        name: frogfishio/kona-user 
          # # Tag for the Docker image
          # tag: # optional
          # # Script body to compute tag name for the Docker image, has context as the main function argument
          # tag script: # optional
          # # Username for Docker registry
        username: frogfishio
          # # Password for Docker registry
        password: ${{ secrets.DOCKERHUB_SECRET }}
          # # Registry URL
          # registry: # optional
          # # Don't skip pull requests
          # include pull requests: # optional
