name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1.1.0
    - uses: actions/checkout@v1
    - name: Install packages
      run: npm install --no-bin-links
    - name: build service
      run: npm build
    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: frogfishio/user
        username: frogfishio
        password: ${{ secrets.DOCKERHUB_SECRET }}